spring:
  profiles:
    active: dev

  mail:
    host: smtp.gmail.com
    port: 587
    username: jaychothiyawala04@gmail.com
    password: xx xxx xx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
